import{a as P,S as h,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(r){if(r.ep)return;r.ep=!0;const a=o(r);fetch(r.href,a)}})();const E="49652753-628f6ab7e356d597b0d2f9b26";let x=15;const b=async(e,t)=>{try{return(await P.get("https://pixabay.com/api/",{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:x,page:t}})).data}catch(o){return console.error("Error fetching images:",o),[]}};let d=new h(".gallery a",{captionsData:"alt",captionDelay:250});function L(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function c(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const $=()=>{const e=document.querySelector(".gallery");e.innerHTML="",g()};function S(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",e.map(({webformatURL:o,largeImageURL:i,tags:r,likes:a,views:s,comments:v,downloads:M})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${o}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
                <p><b>Likes</b><br>${a}</p>
                <p><b>Views</b><br>${s}</p>
                <p><b>Comments</b><br>${v}</p>
                <p><b>Downloads</b><br>${M}</p>
            </div>
      </li>`).join("")),d.refresh()}function q(){d||(d=new h(".gallery a",{captionsData:"alt",captionDelay:250})),d.refresh()}function g(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}}function w(){const e=document.querySelector(".load-more");e&&(e.style.display="flex")}function u(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const m=document.querySelector(".form"),p=document.querySelector(".load-more");let n=1,f="",y=0;c();u();m.addEventListener("submit",async function(e){e.preventDefault();const t=m.querySelector('input[name="search-text"]').value.trim();if(!t){l.error({title:"Error",message:"Please, enter the text for search!"});return}t!==f&&(n=1,$(),g(),f=t),L();try{const o=await b(f,n);if(c(),!o||!o.hits||o.hits.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}const i=o.hits;y=o.totalHits,S(i),q();const r=Math.ceil(y/15);n>=r?u():w()}catch(o){c(),l.error({title:"Error",message:"Illegal operation."}),console.error(o)}});p&&p.addEventListener("click",async()=>{n+=1,L();try{const e=await b(f,n);if(c(),!e||!e.hits||e.hits.length===0){l.warning({title:"Caution",message:"Sorry, no more images available."}),u();return}S(e.hits),q(),g();const t=Math.ceil(y/15);n>=t?u():w()}catch(e){c(),l.error({title:"Error",message:"Error loading more images."}),console.error(e)}});
//# sourceMappingURL=index.js.map
